[project]
name = "miniminitel"
version = "1.0.5"
authors = [
  { name="Portevent" },
]
description = "Simple Minitel interface in Python"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3"
]
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
  "pillow",
  "pyserial"
]

[project.urls]
Homepage = "https://github.com/Portevent/MiniMinitel"
Issues = "https://github.com/Portevent/MiniMinitel/issues"

[build-system]
requires = ["setuptools >= 80.9.0"]
build-backend = "setuptools.build_meta"